export const cityData =  [
    {
        "id": 11789136,
        "name": "Gujarat",
        "latitude": 23.15963,
        "longitude": 72.68451,
        "elevation": 65,
        "feature_code": "PPL",
        "country_code": "IN",
        "admin1_id": 1270770,
        "admin2_id": 1271716,
        "timezone": "Asia/Kolkata",
        "country_id": 1269750,
        "country": "India",
        "admin1": "Gujarat",
        "admin2": "Gandhinagar",
        "current_weather_units":[],
        "current_weather":[]
      },
      {
        "id": 1264527,
        "name": "Chennai",
        "latitude": 13.08784,
        "longitude": 80.27847,
        "elevation": 14,
        "feature_code": "PPLA",
        "country_code": "IN",
        "admin1_id": 1255053,
        "admin2_id": 7646145,
        "timezone": "Asia/Kolkata",
        "population": 4328063,
        "country_id": 1269750,
        "country": "India",
        "admin1": "Tamil Nadu",
        "admin2": "Chennai",
        "current_weather_units":[],
        "current_weather":[]
      },
      {
        "id": 1277333,
        "name": "Bengaluru",
        "latitude": 12.97194,
        "longitude": 77.59369,
        "elevation": 920,
        "feature_code": "PPLA",
        "country_code": "IN",
        "admin1_id": 1267701,
        "admin2_id": 1277331,
        "timezone": "Asia/Kolkata",
        "population": 5104047,
        "country_id": 1269750,
        "country": "India",
        "admin1": "Karnataka",
        "admin2": "Bengaluru Urban",
        "current_weather_units":[],
        "current_weather":[]
      }
        ]